### ISSUE TITLE
Class vs Functional Components

### ISSUE THREAD

**Issue by tanelam** [Vosmash/jammming#4]
https://github.com/Vosmash/jammming/blob/5e16177dffe14e0ee59b356aa61eab137458aa1e/src/components/SearchResults/SearchResults.js#L5-L13

React Components can be declared both as classes and as functions. Functional components are simpler to define but they lack certain features currently available only to class components, and I suggest you use them unless you need state. You can find more info [here!](https://reactjs.org/docs/components-and-props.html) 😀

Ex.

```
const SearchResults = props => {
  return (
    <div className="SearchResults">
      <h2>Results</h2>
        <TrackList
          tracks={props.searchResults}
          onAdd={props.onAdd}
          isRemoval={false}/>
    </div>
  )
}
```

**Comment by Vosmash** [comment]
thanks
